### ISSUE TITLE
Question: What exactly is this project

### ISSUE THREAD

**Issue by AdrianVovk** [endovitskayaV/Kompiler-compiler#1]
What is its goal/purpose?

**Comment by endovitskayaV** [comment]
It is not finished yet. Now it is only possible  to build AST tree, but I'm going to create semantic analyser, error diagnostics, optimizations and I'm still  thinking what it  will compile into.

**Comment by AdrianVovk** [comment]
Any particular reason?

**Comment by endovitskayaV** [comment]
Just learning what is a compiler and how to create it

**Comment by AdrianVovk** [comment]
Are you planning on maintaining it for a while? I have an IDE I'm working on for Kotlin and I haven't been able to figure out how to use the compiler for code completion and such

**Comment by endovitskayaV** [comment]
Probably yes. But I am not going to make it close to perfect because it is just a training task. I have to reach the goal until the end of December and that is all.
